// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payment/v1/payment.proto

package payment_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PayOrderResponse содержит uuid транзакции, которая была создана в результате оплаты заказа
type PayOrderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayOrderResponse) Reset() {
	*x = PayOrderResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResponse) ProtoMessage() {}

func (x *PayOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResponse.ProtoReflect.Descriptor instead.
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PayOrderResponse) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

// PaymentMethod содержит информацию о способе оплаты, который использует пользователь для оплаты заказа
type PaymentMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Method:
	//
	//	*PaymentMethod_Unknown
	//	*PaymentMethod_Card
	//	*PaymentMethod_Sbp
	//	*PaymentMethod_CreditCard
	//	*PaymentMethod_InvestorMoney
	Method        isPaymentMethod_Method `protobuf_oneof:"method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethod) Reset() {
	*x = PaymentMethod{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethod) ProtoMessage() {}

func (x *PaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethod.ProtoReflect.Descriptor instead.
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentMethod) GetMethod() isPaymentMethod_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *PaymentMethod) GetUnknown() string {
	if x != nil {
		if x, ok := x.Method.(*PaymentMethod_Unknown); ok {
			return x.Unknown
		}
	}
	return ""
}

func (x *PaymentMethod) GetCard() string {
	if x != nil {
		if x, ok := x.Method.(*PaymentMethod_Card); ok {
			return x.Card
		}
	}
	return ""
}

func (x *PaymentMethod) GetSbp() string {
	if x != nil {
		if x, ok := x.Method.(*PaymentMethod_Sbp); ok {
			return x.Sbp
		}
	}
	return ""
}

func (x *PaymentMethod) GetCreditCard() string {
	if x != nil {
		if x, ok := x.Method.(*PaymentMethod_CreditCard); ok {
			return x.CreditCard
		}
	}
	return ""
}

func (x *PaymentMethod) GetInvestorMoney() string {
	if x != nil {
		if x, ok := x.Method.(*PaymentMethod_InvestorMoney); ok {
			return x.InvestorMoney
		}
	}
	return ""
}

type isPaymentMethod_Method interface {
	isPaymentMethod_Method()
}

type PaymentMethod_Unknown struct {
	Unknown string `protobuf:"bytes,1,opt,name=unknown,proto3,oneof"`
}

type PaymentMethod_Card struct {
	Card string `protobuf:"bytes,2,opt,name=card,proto3,oneof"`
}

type PaymentMethod_Sbp struct {
	Sbp string `protobuf:"bytes,3,opt,name=sbp,proto3,oneof"`
}

type PaymentMethod_CreditCard struct {
	CreditCard string `protobuf:"bytes,4,opt,name=credit_card,json=creditCard,proto3,oneof"`
}

type PaymentMethod_InvestorMoney struct {
	InvestorMoney string `protobuf:"bytes,5,opt,name=investor_money,json=investorMoney,proto3,oneof"`
}

func (*PaymentMethod_Unknown) isPaymentMethod_Method() {}

func (*PaymentMethod_Card) isPaymentMethod_Method() {}

func (*PaymentMethod_Sbp) isPaymentMethod_Method() {}

func (*PaymentMethod_CreditCard) isPaymentMethod_Method() {}

func (*PaymentMethod_InvestorMoney) isPaymentMethod_Method() {}

// PayOrderRequest содержит информацию о заказе, который пользователь хочет оплатить, а также информацию о способе оплаты, который он использует
type PayOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PaymentMethod *PaymentMethod         `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRequest) Reset() {
	*x = PayOrderRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRequest) ProtoMessage() {}

func (x *PayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRequest.ProtoReflect.Descriptor instead.
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PayOrderRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *PayOrderRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *PayOrderRequest) GetPaymentMethod() *PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\"=\n" +
	"\x10PayOrderResponse\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\"\xab\x01\n" +
	"\rPaymentMethod\x12\x1a\n" +
	"\aunknown\x18\x01 \x01(\tH\x00R\aunknown\x12\x14\n" +
	"\x04card\x18\x02 \x01(\tH\x00R\x04card\x12\x12\n" +
	"\x03sbp\x18\x03 \x01(\tH\x00R\x03sbp\x12!\n" +
	"\vcredit_card\x18\x04 \x01(\tH\x00R\n" +
	"creditCard\x12'\n" +
	"\x0einvestor_money\x18\x05 \x01(\tH\x00R\rinvestorMoneyB\b\n" +
	"\x06method\"\x8f\x01\n" +
	"\x0fPayOrderRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12@\n" +
	"\x0epayment_method\x18\x03 \x01(\v2\x19.payment.v1.PaymentMethodR\rpaymentMethod2W\n" +
	"\x0ePaymentService\x12E\n" +
	"\bPayOrder\x12\x1b.payment.v1.PayOrderRequest\x1a\x1c.payment.v1.PayOrderResponseBIZGgithub.com/m4kson/rocket-factory/shared/pkg/proto/payment/v1;payment_v1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payment_v1_payment_proto_goTypes = []any{
	(*PayOrderResponse)(nil), // 0: payment.v1.PayOrderResponse
	(*PaymentMethod)(nil),    // 1: payment.v1.PaymentMethod
	(*PayOrderRequest)(nil),  // 2: payment.v1.PayOrderRequest
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	1, // 0: payment.v1.PayOrderRequest.payment_method:type_name -> payment.v1.PaymentMethod
	2, // 1: payment.v1.PaymentService.PayOrder:input_type -> payment.v1.PayOrderRequest
	0, // 2: payment.v1.PaymentService.PayOrder:output_type -> payment.v1.PayOrderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	file_payment_v1_payment_proto_msgTypes[1].OneofWrappers = []any{
		(*PaymentMethod_Unknown)(nil),
		(*PaymentMethod_Card)(nil),
		(*PaymentMethod_Sbp)(nil),
		(*PaymentMethod_CreditCard)(nil),
		(*PaymentMethod_InvestorMoney)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
