// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	internalmodel "github.com/m4kson/rocket-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	model "github.com/m4kson/rocket-factory/order/internal/repository/model"

	uuid "github.com/google/uuid"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CancelOrderById provides a mock function with given fields: ctx, orderId
func (_m *OrderRepository) CancelOrderById(ctx context.Context, orderId uuid.UUID) error {
	ret := _m.Called(ctx, orderId)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, orderId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_CancelOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderById'
type OrderRepository_CancelOrderById_Call struct {
	*mock.Call
}

// CancelOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
func (_e *OrderRepository_Expecter) CancelOrderById(ctx interface{}, orderId interface{}) *OrderRepository_CancelOrderById_Call {
	return &OrderRepository_CancelOrderById_Call{Call: _e.mock.On("CancelOrderById", ctx, orderId)}
}

func (_c *OrderRepository_CancelOrderById_Call) Run(run func(ctx context.Context, orderId uuid.UUID)) *OrderRepository_CancelOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderRepository_CancelOrderById_Call) Return(_a0 error) *OrderRepository_CancelOrderById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_CancelOrderById_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *OrderRepository_CancelOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepository) CreateOrder(ctx context.Context, order model.CreateOrderRequest) (internalmodel.CreateOrderRes, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 internalmodel.CreateOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) (internalmodel.CreateOrderRes, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) internalmodel.CreateOrderRes); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(internalmodel.CreateOrderRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.CreateOrderRequest
func (_e *OrderRepository_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, order model.CreateOrderRequest)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 internalmodel.CreateOrderRes, _a1 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, model.CreateOrderRequest) (internalmodel.CreateOrderRes, error)) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderById provides a mock function with given fields: ctx, orderId
func (_m *OrderRepository) GetOrderById(ctx context.Context, orderId uuid.UUID) (internalmodel.GetOrderResponse, error) {
	ret := _m.Called(ctx, orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderById")
	}

	var r0 internalmodel.GetOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (internalmodel.GetOrderResponse, error)); ok {
		return rf(ctx, orderId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) internalmodel.GetOrderResponse); ok {
		r0 = rf(ctx, orderId)
	} else {
		r0 = ret.Get(0).(internalmodel.GetOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderById'
type OrderRepository_GetOrderById_Call struct {
	*mock.Call
}

// GetOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
func (_e *OrderRepository_Expecter) GetOrderById(ctx interface{}, orderId interface{}) *OrderRepository_GetOrderById_Call {
	return &OrderRepository_GetOrderById_Call{Call: _e.mock.On("GetOrderById", ctx, orderId)}
}

func (_c *OrderRepository_GetOrderById_Call) Run(run func(ctx context.Context, orderId uuid.UUID)) *OrderRepository_GetOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderRepository_GetOrderById_Call) Return(_a0 internalmodel.GetOrderResponse, _a1 error) *OrderRepository_GetOrderById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrderById_Call) RunAndReturn(run func(context.Context, uuid.UUID) (internalmodel.GetOrderResponse, error)) *OrderRepository_GetOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrderById provides a mock function with given fields: ctx, orderId, paymentMethod, transactionId
func (_m *OrderRepository) PayOrderById(ctx context.Context, orderId uuid.UUID, paymentMethod internalmodel.PaymentMethod, transactionId uuid.UUID) (internalmodel.PayOrderRes, error) {
	ret := _m.Called(ctx, orderId, paymentMethod, transactionId)

	if len(ret) == 0 {
		panic("no return value specified for PayOrderById")
	}

	var r0 internalmodel.PayOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, internalmodel.PaymentMethod, uuid.UUID) (internalmodel.PayOrderRes, error)); ok {
		return rf(ctx, orderId, paymentMethod, transactionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, internalmodel.PaymentMethod, uuid.UUID) internalmodel.PayOrderRes); ok {
		r0 = rf(ctx, orderId, paymentMethod, transactionId)
	} else {
		r0 = ret.Get(0).(internalmodel.PayOrderRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, internalmodel.PaymentMethod, uuid.UUID) error); ok {
		r1 = rf(ctx, orderId, paymentMethod, transactionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_PayOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrderById'
type OrderRepository_PayOrderById_Call struct {
	*mock.Call
}

// PayOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
//   - paymentMethod internalmodel.PaymentMethod
//   - transactionId uuid.UUID
func (_e *OrderRepository_Expecter) PayOrderById(ctx interface{}, orderId interface{}, paymentMethod interface{}, transactionId interface{}) *OrderRepository_PayOrderById_Call {
	return &OrderRepository_PayOrderById_Call{Call: _e.mock.On("PayOrderById", ctx, orderId, paymentMethod, transactionId)}
}

func (_c *OrderRepository_PayOrderById_Call) Run(run func(ctx context.Context, orderId uuid.UUID, paymentMethod internalmodel.PaymentMethod, transactionId uuid.UUID)) *OrderRepository_PayOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(internalmodel.PaymentMethod), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *OrderRepository_PayOrderById_Call) Return(_a0 internalmodel.PayOrderRes, _a1 error) *OrderRepository_PayOrderById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_PayOrderById_Call) RunAndReturn(run func(context.Context, uuid.UUID, internalmodel.PaymentMethod, uuid.UUID) (internalmodel.PayOrderRes, error)) *OrderRepository_PayOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, orderId, status
func (_m *OrderRepository) UpdateStatus(ctx context.Context, orderId uuid.UUID, status internalmodel.OrderStatus) (*internalmodel.GetOrderResponse, error) {
	ret := _m.Called(ctx, orderId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *internalmodel.GetOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, internalmodel.OrderStatus) (*internalmodel.GetOrderResponse, error)); ok {
		return rf(ctx, orderId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, internalmodel.OrderStatus) *internalmodel.GetOrderResponse); ok {
		r0 = rf(ctx, orderId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalmodel.GetOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, internalmodel.OrderStatus) error); ok {
		r1 = rf(ctx, orderId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type OrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
//   - status internalmodel.OrderStatus
func (_e *OrderRepository_Expecter) UpdateStatus(ctx interface{}, orderId interface{}, status interface{}) *OrderRepository_UpdateStatus_Call {
	return &OrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orderId, status)}
}

func (_c *OrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, orderId uuid.UUID, status internalmodel.OrderStatus)) *OrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(internalmodel.OrderStatus))
	})
	return _c
}

func (_c *OrderRepository_UpdateStatus_Call) Return(_a0 *internalmodel.GetOrderResponse, _a1 error) *OrderRepository_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, internalmodel.OrderStatus) (*internalmodel.GetOrderResponse, error)) *OrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
