// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrderByUUID implements cancelOrderByUUID operation.
	//
	// Отменить заказ по UUID.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrderByUUID(ctx context.Context, params CancelOrderByUUIDParams) (CancelOrderByUUIDRes, error)
	// CreateOrder implements createOrder operation.
	//
	// Создать новый заказ.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderByUUID implements getOrderByUUID operation.
	//
	// Получить информацию о заказе по UUID.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUUID(ctx context.Context, params GetOrderByUUIDParams) (GetOrderByUUIDRes, error)
	// PayOrderByUUID implements payOrderByUUID operation.
	//
	// Оплатить заказ по UUID.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrderByUUID(ctx context.Context, req *PayOrderRequest, params PayOrderByUUIDParams) (PayOrderByUUIDRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
