// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrderByUUID implements cancelOrderByUUID operation.
//
// Отменить заказ по UUID.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrderByUUID(ctx context.Context, params CancelOrderByUUIDParams) (r CancelOrderByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements createOrder operation.
//
// Создать новый заказ.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByUUID implements getOrderByUUID operation.
//
// Получить информацию о заказе по UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByUUID(ctx context.Context, params GetOrderByUUIDParams) (r GetOrderByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrderByUUID implements payOrderByUUID operation.
//
// Оплатить заказ по UUID.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrderByUUID(ctx context.Context, req *PayOrderRequest, params PayOrderByUUIDParams) (r PayOrderByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}
