// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Ref: #/components/schemas/bad_gateway_error
type BadGatewayError struct {
	// HTTP status code representing the error type (e.g., 502 for Bad Gateway).
	Code int `json:"code"`
	// A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadGatewayError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadGatewayError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadGatewayError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadGatewayError) SetMessage(val string) {
	s.Message = val
}

func (*BadGatewayError) cancelOrderByUUIDRes() {}
func (*BadGatewayError) createOrderRes()       {}
func (*BadGatewayError) getOrderByUUIDRes()    {}
func (*BadGatewayError) payOrderByUUIDRes()    {}

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP status code representing the error type (e.g., 400  for Bad Request).
	Code int `json:"code"`
	// A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) createOrderRes()    {}
func (*BadRequestError) payOrderByUUIDRes() {}

// CancelOrderByUUIDNoContent is response for CancelOrderByUUID operation.
type CancelOrderByUUIDNoContent struct{}

func (*CancelOrderByUUIDNoContent) cancelOrderByUUIDRes() {}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	// HTTP status code representing the error type (e.g., 409 for Conflict).
	Code int `json:"code"`
	// A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderByUUIDRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// UUID пользователя, который создает заказ.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID деталей, которые включены в заказ.
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// UUID созданного заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Общая стоимость заказа.
	TotalPrice float32 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float32 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #/components/schemas/forbidden_error
type ForbiddenError struct {
	// HTTP status code representing the error type (e.g., 403 for Forbidden error).
	Code int `json:"code"`
	// A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ForbiddenError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ForbiddenError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ForbiddenError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ForbiddenError) SetMessage(val string) {
	s.Message = val
}

func (*ForbiddenError) cancelOrderByUUIDRes() {}
func (*ForbiddenError) createOrderRes()       {}
func (*ForbiddenError) getOrderByUUIDRes()    {}
func (*ForbiddenError) payOrderByUUIDRes()    {}

// Ref: #/components/schemas/get_order_response
type GetOrderResponse struct {
	// Уникальный идентификатор заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Уникальный идентификатор пользователя, который
	// создал заказ.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список уникальных идентификаторов деталей,
	// включенных в заказ.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Общая стоимость заказа, рассчитанная на основе цен
	// деталей и их количества.
	TotalPrice float32 `json:"total_price"`
	// Идентификатор транзакции, который был сгенерирован
	// при оплате заказа.
	TransactionUUID OptUUID `json:"transaction_uuid"`
	// Метод оплаты, который был использован для оплаты
	// заказа.
	PaymentMethod PaymentMethod `json:"payment_method"`
	// Текущий статус заказа, который может изменяться в
	// процессе его обработки.
	Status OrderStatus `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *GetOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *GetOrderResponse) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *GetOrderResponse) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *GetOrderResponse) GetTotalPrice() float32 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *GetOrderResponse) GetTransactionUUID() OptUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *GetOrderResponse) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *GetOrderResponse) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *GetOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *GetOrderResponse) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *GetOrderResponse) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *GetOrderResponse) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *GetOrderResponse) SetTransactionUUID(val OptUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *GetOrderResponse) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *GetOrderResponse) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*GetOrderResponse) getOrderByUUIDRes() {}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP status code representing the error type (e.g., 500 for Internal Server Error).
	Code int `json:"code"`
	// A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) cancelOrderByUUIDRes() {}
func (*InternalServerError) createOrderRes()       {}
func (*InternalServerError) getOrderByUUIDRes()    {}
func (*InternalServerError) payOrderByUUIDRes()    {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP status code representing the error type (e.g., 404 for Not Found).
	Code int `json:"code"`
	// A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderByUUIDRes() {}
func (*NotFoundError) getOrderByUUIDRes()    {}
func (*NotFoundError) payOrderByUUIDRes()    {}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Статус заказа.
// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusUNKNOWN        OrderStatus = "UNKNOWN"
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusUNKNOWN,
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusUNKNOWN:
		return []byte(s), nil
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusUNKNOWN:
		*s = OrderStatusUNKNOWN
		return nil
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	// Метод оплаты, который будет использоваться для
	// оплаты заказа.
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	// Идентификатор транзакции, который был сгенерирован
	// при оплате заказа.
	TransactionID uuid.UUID `json:"transaction_id"`
}

// GetTransactionID returns the value of TransactionID.
func (s *PayOrderResponse) GetTransactionID() uuid.UUID {
	return s.TransactionID
}

// SetTransactionID sets the value of TransactionID.
func (s *PayOrderResponse) SetTransactionID(val uuid.UUID) {
	s.TransactionID = val
}

func (*PayOrderResponse) payOrderByUUIDRes() {}

// Метод оплаты.
// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodUNKNOWN       PaymentMethod = "UNKNOWN"
	PaymentMethodCARD          PaymentMethod = "CARD"
	PaymentMethodSBP           PaymentMethod = "SBP"
	PaymentMethodCREDITCARD    PaymentMethod = "CREDIT_CARD"
	PaymentMethodINVESTORMONEY PaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodUNKNOWN,
		PaymentMethodCARD,
		PaymentMethodSBP,
		PaymentMethodCREDITCARD,
		PaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodUNKNOWN:
		return []byte(s), nil
	case PaymentMethodCARD:
		return []byte(s), nil
	case PaymentMethodSBP:
		return []byte(s), nil
	case PaymentMethodCREDITCARD:
		return []byte(s), nil
	case PaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodUNKNOWN:
		*s = PaymentMethodUNKNOWN
		return nil
	case PaymentMethodCARD:
		*s = PaymentMethodCARD
		return nil
	case PaymentMethodSBP:
		*s = PaymentMethodSBP
		return nil
	case PaymentMethodCREDITCARD:
		*s = PaymentMethodCREDITCARD
		return nil
	case PaymentMethodINVESTORMONEY:
		*s = PaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/rate_limit_error
type RateLimitError struct {
	// HTTP status code representing the error type (e.g., 429 for Too Many Requests).
	Code int `json:"code"`
	// A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *RateLimitError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *RateLimitError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *RateLimitError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *RateLimitError) SetMessage(val string) {
	s.Message = val
}

func (*RateLimitError) cancelOrderByUUIDRes() {}
func (*RateLimitError) createOrderRes()       {}
func (*RateLimitError) getOrderByUUIDRes()    {}
func (*RateLimitError) payOrderByUUIDRes()    {}

// Ref: #/components/schemas/unauthorized_error
type UnauthorizedError struct {
	// HTTP status code representing the error type (e.g., 401 for Unauthorized).
	Code int `json:"code"`
	// A human-readable message providing more details about the error.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *UnauthorizedError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *UnauthorizedError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *UnauthorizedError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *UnauthorizedError) SetMessage(val string) {
	s.Message = val
}

func (*UnauthorizedError) cancelOrderByUUIDRes() {}
func (*UnauthorizedError) createOrderRes()       {}
func (*UnauthorizedError) getOrderByUUIDRes()    {}
func (*UnauthorizedError) payOrderByUUIDRes()    {}
