// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/m4kson/rocket-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrderById provides a mock function with given fields: ctx, orderId
func (_m *OrderService) CancelOrderById(ctx context.Context, orderId uuid.UUID) error {
	ret := _m.Called(ctx, orderId)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, orderId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_CancelOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderById'
type OrderService_CancelOrderById_Call struct {
	*mock.Call
}

// CancelOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
func (_e *OrderService_Expecter) CancelOrderById(ctx interface{}, orderId interface{}) *OrderService_CancelOrderById_Call {
	return &OrderService_CancelOrderById_Call{Call: _e.mock.On("CancelOrderById", ctx, orderId)}
}

func (_c *OrderService_CancelOrderById_Call) Run(run func(ctx context.Context, orderId uuid.UUID)) *OrderService_CancelOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderService_CancelOrderById_Call) Return(_a0 error) *OrderService_CancelOrderById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_CancelOrderById_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *OrderService_CancelOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderService) CreateOrder(ctx context.Context, order model.CreateOrderRequest) (model.CreateOrderRes, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 model.CreateOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) (model.CreateOrderRes, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) model.CreateOrderRes); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(model.CreateOrderRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.CreateOrderRequest
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, order model.CreateOrderRequest)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(_a0 model.CreateOrderRes, _a1 error) *OrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, model.CreateOrderRequest) (model.CreateOrderRes, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderById provides a mock function with given fields: ctx, orderId
func (_m *OrderService) GetOrderById(ctx context.Context, orderId uuid.UUID) (model.GetOrderResponse, error) {
	ret := _m.Called(ctx, orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderById")
	}

	var r0 model.GetOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.GetOrderResponse, error)); ok {
		return rf(ctx, orderId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.GetOrderResponse); ok {
		r0 = rf(ctx, orderId)
	} else {
		r0 = ret.Get(0).(model.GetOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderById'
type OrderService_GetOrderById_Call struct {
	*mock.Call
}

// GetOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
func (_e *OrderService_Expecter) GetOrderById(ctx interface{}, orderId interface{}) *OrderService_GetOrderById_Call {
	return &OrderService_GetOrderById_Call{Call: _e.mock.On("GetOrderById", ctx, orderId)}
}

func (_c *OrderService_GetOrderById_Call) Run(run func(ctx context.Context, orderId uuid.UUID)) *OrderService_GetOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderService_GetOrderById_Call) Return(_a0 model.GetOrderResponse, _a1 error) *OrderService_GetOrderById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrderById_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.GetOrderResponse, error)) *OrderService_GetOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrderById provides a mock function with given fields: ctx, orderId, paymentMethod, userId
func (_m *OrderService) PayOrderById(ctx context.Context, orderId uuid.UUID, paymentMethod model.PaymentMethod, userId uuid.UUID) (model.PayOrderRes, error) {
	ret := _m.Called(ctx, orderId, paymentMethod, userId)

	if len(ret) == 0 {
		panic("no return value specified for PayOrderById")
	}

	var r0 model.PayOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod, uuid.UUID) (model.PayOrderRes, error)); ok {
		return rf(ctx, orderId, paymentMethod, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod, uuid.UUID) model.PayOrderRes); ok {
		r0 = rf(ctx, orderId, paymentMethod, userId)
	} else {
		r0 = ret.Get(0).(model.PayOrderRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.PaymentMethod, uuid.UUID) error); ok {
		r1 = rf(ctx, orderId, paymentMethod, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_PayOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrderById'
type OrderService_PayOrderById_Call struct {
	*mock.Call
}

// PayOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
//   - paymentMethod model.PaymentMethod
//   - userId uuid.UUID
func (_e *OrderService_Expecter) PayOrderById(ctx interface{}, orderId interface{}, paymentMethod interface{}, userId interface{}) *OrderService_PayOrderById_Call {
	return &OrderService_PayOrderById_Call{Call: _e.mock.On("PayOrderById", ctx, orderId, paymentMethod, userId)}
}

func (_c *OrderService_PayOrderById_Call) Run(run func(ctx context.Context, orderId uuid.UUID, paymentMethod model.PaymentMethod, userId uuid.UUID)) *OrderService_PayOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.PaymentMethod), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *OrderService_PayOrderById_Call) Return(_a0 model.PayOrderRes, _a1 error) *OrderService_PayOrderById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_PayOrderById_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.PaymentMethod, uuid.UUID) (model.PayOrderRes, error)) *OrderService_PayOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
