// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrderConsumerService is an autogenerated mock type for the OrderConsumerService type
type OrderConsumerService struct {
	mock.Mock
}

type OrderConsumerService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderConsumerService) EXPECT() *OrderConsumerService_Expecter {
	return &OrderConsumerService_Expecter{mock: &_m.Mock}
}

// RunConsumer provides a mock function with given fields: ctx
func (_m *OrderConsumerService) RunConsumer(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunConsumer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderConsumerService_RunConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConsumer'
type OrderConsumerService_RunConsumer_Call struct {
	*mock.Call
}

// RunConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderConsumerService_Expecter) RunConsumer(ctx interface{}) *OrderConsumerService_RunConsumer_Call {
	return &OrderConsumerService_RunConsumer_Call{Call: _e.mock.On("RunConsumer", ctx)}
}

func (_c *OrderConsumerService_RunConsumer_Call) Run(run func(ctx context.Context)) *OrderConsumerService_RunConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderConsumerService_RunConsumer_Call) Return(_a0 error) *OrderConsumerService_RunConsumer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderConsumerService_RunConsumer_Call) RunAndReturn(run func(context.Context) error) *OrderConsumerService_RunConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderConsumerService creates a new instance of OrderConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderConsumerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderConsumerService {
	mock := &OrderConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
